SHELL :=bash 
OUR_DIR :=out
DIST_DIR :=dist

.PHONY:build
build:
	@echo "build"
.PHONY:test 
test:
	@echo "test"
.PHONY:package 
package:
	@echo "package"
.PHONY:clean 
clean:
	@echo "clean"
	rm -rf $(OUR_DIR) $(DIST_DIR)
.PHONY:help 
help:
	@echo "help"
.PHONY:lint 
lint:
	@echo "lint"

